[package]
name = "tidyql-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
color-eyre = "0.6.3"
crossterm = "0.28.1"
difference = "2.0.0"
env_logger = "0.11.6"
log = "0.4.25"
ratatui = "0.29.0"
sqlformat = "0.3.5"
syntect = "5.2.0"
